apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: argocd
spec:
  project: default

  sources:
    # ✅ Helm chart source
    - repoURL: https://stefanprodan.github.io/podinfo
      chart: podinfo
      targetRevision: "*"
      helm:
        valueFiles:
          - $values/values.yaml   # 👈 adjust path

    # ✅ Your Git repo (values source)
    - repoURL: https://github.com/yossisp1972/gitops.git
      targetRevision: HEAD
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: podinfo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
